---
all:
  vars: 
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
manager:
  vars:
    ansible_connection: local
  hosts: 127.0.0.1
worker:
  hosts:
      workers1:
        ansible_host: 192.168.1.6
      workers2:
        ansible_host: 192.168.1.7
      worker3:
        ansible_host: 192.168.1.8
