- hosts: all
  become: true
  tasks:
    - name: Upgrade pip3
      shell: "python3.8 -m pip install pip --upgrade"

    - name: Ensure Python pip packages are installed
      pip:
        name: "{{ packages }}"
        executable: /usr/local/bin/pip3.8
      vars:
        packages:
        - docker
        - docker-compose
- hosts: manager
  become: true
  tasks:

    - name: Swarm init
      command: docker swarm init
